import type { MetadataRoute } from "next";

const BLOCKED_BOTS = [
  "GPTBot",
  "ChatGPT-User",
  "OAI-SearchBot",
  "ClaudeBot",
  "Claude-Web",
  "Claude-User",
  "Claude-SearchBot",
  "anthropic-ai",
  "Google-Extended",
  "GoogleOther",
  "Googlebot",
  "Googlebot-Image",
  "Googlebot-Video",
  "Googlebot-News",
  "AdsBot-Google",
  "Mediapartners-Google",
  "Bingbot",
  "BingPreview",
  "msnbot",
  "Slurp",
  "DuckDuckBot",
  "DuckAssistBot",
  "Baiduspider",
  "YandexBot",
  "Sogou",
  "Exabot",
  "facebot",
  "ia_archiver",
  "PerplexityBot",
  "Perplexity-User",
  "Applebot",
  "Applebot-Extended",
  "Amazonbot",
  "Bytespider",
  "ByteDance",
  "TikTokSpider",
  "CCBot",
  "cohere-ai",
  "cohere-training-data-crawler",
  "Diffbot",
  "FacebookBot",
  "FriendlyCrawler",
  "Meta-ExternalAgent",
  "Meta-ExternalFetcher",
  "ImagesiftBot",
  "img2dataset",
  "Kangaroo Bot",
  "Mistral",
  "MistralAI-User",
  "OmgiliBot",
  "Omgili",
  "PanguBot",
  "PetalBot",
  "Scrapy",
  "SemrushBot",
  "AhrefsBot",
  "MJ12bot",
  "DataForSeoBot",
  "Timpibot",
  "VelenPublicWebCrawler",
  "Webzio-Extended",
  "YouBot",
  "iaskspider/2.0",
  "ISSCyberRiskCrawler",
  "news-please",
  "peer39_crawler",
  "peer39_crawler/1.0",
  "QuillBot",
  "SiteAuditBot",
  "Twitterbot",
  "LinkedInBot",
  "PiplBot",
  "Pinterestbot",
  "TelegramBot",
  "WhatsApp",
  "Discordbot",
  "Slackbot",
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      ...BLOCKED_BOTS.map((userAgent) => ({
        userAgent,
        disallow: "/",
      })),
      {
        userAgent: "*",
        disallow: "/",
      },
    ],
    sitemap: "https://postab.app/sitemap.xml",
    host: "https://postab.app",
  };
}
